ALTER TABLE chapters ADD COLUMN parent_id INT NULL DEFAULT NULL;
ALTER TABLE chapters ADD COLUMN level INT NOT NULL DEFAULT 1;
ALTER TABLE chapters ADD CONSTRAINT fk_parent_chapter FOREIGN KEY (parent_id) REFERENCES chapters(id) ON DELETE CASCADE;
